title: Bright Ahiaba
logo: Data.jpg
description: I'm data analyst with deep experience in analyzing data usomg excel for report automation and power Bi for business insight.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
